import db from "./initdb.js";

const employees = [
  { name: "Priya Patel", department: "Engineering", riskLevel: "high" },
  { name: "João Silva", department: "Finance", riskLevel: "medium" },
  { name: "Fatima Al-Rashid", department: "Marketing", riskLevel: "low" },
  { name: "Oluwaseun Adeyemi", department: "Operations", riskLevel: "high" },
  { name: "Chen Wei-Lin", department: "HR", riskLevel: "medium" },
  { name: "James Wilson", department: "Finance", riskLevel: "medium" },
  { name: "Sophia Martinez", department: "Marketing", riskLevel: "low" },
  { name: "Ethan Brown", department: "Operations", riskLevel: "high" },
  { name: "Ava Johnson", department: "Human Resources", riskLevel: "low" },
  { name: "Liam Thompson", department: "Engineering", riskLevel: "medium" },
  { name: "Isabella Davis", department: "Customer Support", riskLevel: "high" },
  { name: "Noah Anderson", department: "Logistics", riskLevel: "medium" },
  { name: "Mia Rodriguez", department: "Legal", riskLevel: "low" },
  { name: "Lucas Lee", department: "Engineering", riskLevel: "high" },
  { name: "Amelia Harris", department: "Finance", riskLevel: "medium" },
  { name: "Benjamin Clark", department: "Operations", riskLevel: "low" },
  { name: "Olivia Lewis", department: "Design", riskLevel: "high" },
  { name: "Alexander Young", department: "IT", riskLevel: "medium" },
  { name: "Charlotte Walker", department: "Procurement", riskLevel: "low" },
  { name: "Daniel Hall", department: "Research", riskLevel: "high" },
  { name: "Harper Allen", department: "Sales", riskLevel: "medium" },
  { name: "Matthew Wright", department: "Engineering", riskLevel: "low" },
  { name: "Ella Scott", department: "Marketing", riskLevel: "high" },
  { name: "Henry Green", department: "Finance", riskLevel: "medium" },
  { name: "Grace Adams", department: "HR", riskLevel: "low" },
];

db.prepare(`DELETE FROM employees`).run();
db.prepare(`DELETE FROM sqlite_sequence WHERE name='employees'`).run();

const insertEmployee = db.prepare(`
    INSERT INTO employees (name, department, riskLevel)
    VALUES (@name, @department, @riskLevel)
    `);

const insertManyEmployees = db.transaction((rows) => {
  for (const row of rows) insertEmployee.run(row);
});

insertManyEmployees(employees);

console.log("✅ Database seeded with employees!");

const users = [
  {
    name: "Maha Magdy",
    email: "maha.magdy@company.com",
    role: "admin",
    employee_id: null,
  },
  {
    name: "Bob Charlie",
    email: "bob.charlie@company.com",
    role: "admin",
    employee_id: null,
  },
  {
    name: "James Wilson",
    email: "james.wilson@company.com",
    role: "employee",
    employee_id: 6,
  },
];

db.prepare(`DELETE FROM users`).run();

const insertUser = db.prepare(
  `
      INSERT INTO users (name, email, role, employee_id)
      VALUES (@name, @email, @role, @employee_id)
      `
);

const insertManyUsers = db.transaction((rows) => {
  for (const row of rows) insertUser.run(row);
});

insertManyUsers(users);

console.log("✅ Database seeded with users!");

const suggestions = [
  {
    created_at: "2024-01-15T09:00:00Z",
    updated_at: "2024-01-15T09:00:00Z",
    employee_id: 1,
    type: "equipment",
    description:
      "Replace standard peripherals with ergonomic keyboard and mouse to reduce wrist strain",
    status: "pending",
    completed_at: null,
    priority: "high",
    source: "vida",
    notes: "",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-15T09:00:00Z",
    updated_at: "2024-01-18T14:30:00Z",
    employee_id: 2,
    type: "exercise",
    description: "Daily 10-minute wrist and forearm strengthening routine",
    status: "in_progress",
    completed_at: null,
    priority: "high",
    source: "vida",
    notes: "Employee reports improvement in wrist comfort",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-10T11:00:00Z",
    updated_at: "2024-01-20T16:00:00Z",
    employee_id: 3,
    type: "behavioural",
    description:
      "Take 2-minute break every 30 minutes to stretch and rest eyes",
    status: "completed",
    completed_at: null,
    completed_at: null,
    completed_at: "2024-01-20T16:00:00Z",
    priority: "medium",
    source: "vida",
    notes: "Using Pomodoro timer app successfully",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-16T10:30:00Z",
    updated_at: "2024-01-19T09:15:00Z",
    employee_id: 4,
    type: "equipment",
    description:
      "Install adjustable monitor arm to achieve proper eye level (top of screen at eye height)",
    status: "in_progress",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "Order placed, awaiting delivery",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-17T08:00:00Z",
    updated_at: "2024-01-17T08:00:00Z",
    employee_id: 5,
    type: "lifestyle",
    description:
      "Use supportive pillow and maintain neutral spine position during sleep",
    status: "pending",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-14T13:00:00Z",
    updated_at: "2024-01-21T10:00:00Z",
    employee_id: 6,
    type: "exercise",
    description:
      "Specific core exercises 3x per week as demonstrated in VIDA app",
    status: "in_progress",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "Finding morning sessions work best",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-20T15:30:00Z",
    updated_at: "2024-01-20T15:30:00Z",
    employee_id: 7,
    type: "behavioural",
    description: "Set hourly reminders to check and correct sitting posture",
    status: "pending",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "Suggested after workplace assessment",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-12T09:00:00Z",
    updated_at: "2024-01-12T09:00:00Z",
    employee_id: 8,
    type: "equipment",
    description:
      "Provide sit-stand desk converter to alternate positions throughout the day",
    status: "pending",
    completed_at: null,
    priority: "high",
    source: "vida",
    notes: "",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-08T10:00:00Z",
    updated_at: "2024-01-15T14:00:00Z",
    employee_id: 9,
    type: "equipment",
    description: "Ergonomic lumbar support for existing office chair",
    status: "completed",
    completed_at: null,
    completed_at: "2024-01-15T14:00:00Z",
    priority: "high",
    source: "admin",
    createdBy: "hsmanager@company.com",
    notes: "Employee reports significant improvement",
    creator_admin_id: 1,
    last_updater_admin_id: 1,
  },
  {
    created_at: "2024-01-13T11:00:00Z",
    updated_at: "2024-01-20T09:00:00Z",
    employee_id: 10,
    type: "lifestyle",
    description:
      "Aim for 2L of water daily to maintain disc hydration and reduce back stiffness",
    status: "in_progress",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "Using water tracking app",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-20T08:00:00Z",
    updated_at: "2024-01-20T08:00:00Z",
    employee_id: 11,
    type: "lifestyle",
    description: "Limit to 2 cups of coffee daily to reduce muscle tension",
    status: "pending",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-18T10:00:00Z",
    updated_at: "2024-01-21T11:30:00Z",
    employee_id: 12,
    type: "exercise",
    description:
      "20-20-20 rule: Every 20 minutes, look at something 20 feet away for 20 seconds",
    status: "in_progress",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "Reminder app installed",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2023-12-15T09:00:00Z",
    updated_at: "2023-12-15T09:00:00Z",
    employee_id: 13,
    type: "equipment",
    description:
      "Adjustable document holder to reduce neck strain when referencing papers",
    status: "overdue",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "Budget approval pending",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-01-08T10:00:00Z",
    updated_at: "2024-01-15T14:00:00Z",
    employee_id: 9,
    type: "equipment",
    description: "Ergonomic lumbar support for existing office chair",
    status: "completed",
    completed_at: null,
    completed_at: "2024-01-15T14:00:00Z",
    priority: "high",
    source: "admin",
    notes: "Employee reports significant improvement",
    creator_admin_id: 1,
    last_updater_admin_id: 1,
  },
  {
    created_at: "2024-01-13T11:00:00Z",
    updated_at: "2024-01-20T09:00:00Z",
    employee_id: 10,
    type: "lifestyle",
    description:
      "Aim for 2L of water daily to maintain disc hydration and reduce back stiffness",
    status: "in_progress",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "Using water tracking app",
    creator_admin_id: null,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-02-01T09:30:00Z",
    updated_at: "2024-02-05T15:00:00Z",
    employee_id: 1,
    type: "exercise",
    description: "Daily 10-minute stretching routine for lower back",
    status: "pending",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "To be started next week",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-02-03T12:00:00Z",
    updated_at: "2024-02-06T12:30:00Z",
    employee_id: 2,
    type: "equipment",
    description: "Adjustable standing desk",
    status: "completed",
    completed_at: null,
    completed_at: "2024-02-06T12:30:00Z",
    priority: "high",
    source: "admin",
    notes: "Delivered and installed",
    creator_admin_id: 2,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-02-04T08:00:00Z",
    updated_at: "2024-02-10T10:15:00Z",
    employee_id: 3,
    type: "behavioural",
    description: "Take 5-minute breaks every hour",
    status: "overdue",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "Employee not logging breaks",
    creator_admin_id: null,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-02-07T14:00:00Z",
    updated_at: "2024-02-09T16:30:00Z",
    employee_id: 4,
    type: "exercise",
    description: "Add core strengthening workout twice per week",
    status: "in_progress",
    completed_at: null,
    priority: "medium",
    source: "admin",
    notes: "Employee attending gym sessions",
    creator_admin_id: 2,
    last_updater_admin_id: 1,
  },
  {
    created_at: "2024-02-09T10:30:00Z",
    updated_at: "2024-02-11T09:15:00Z",
    employee_id: 5,
    type: "equipment",
    description: "Wrist support keyboard",
    status: "pending",
    completed_at: null,
    priority: "low",
    source: "admin",
    notes: "Requested in procurement queue",
    creator_admin_id: 1,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-02-12T11:00:00Z",
    updated_at: "2024-02-18T13:45:00Z",
    employee_id: 6,
    type: "behavioural",
    description: "Encourage walking meetings",
    status: "completed",
    completed_at: null,
    completed_at: "2024-02-18T13:45:00Z",
    priority: "medium",
    source: "vida",
    notes: "Employee enjoys outdoor walks",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-02-13T09:15:00Z",
    updated_at: "2024-02-20T14:00:00Z",
    employee_id: 7,
    type: "exercise",
    description: "Yoga sessions twice weekly",
    status: "in_progress",
    completed_at: null,
    priority: "high",
    source: "admin",
    notes: "Signed up to office yoga program",
    creator_admin_id: 2,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-02-15T10:45:00Z",
    updated_at: "2024-02-22T11:20:00Z",
    employee_id: 8,
    type: "equipment",
    description: "Monitor riser for better posture",
    status: "pending",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "To be ordered",
    creator_admin_id: null,
    last_updater_admin_id: 1,
  },
  {
    created_at: "2024-02-18T12:30:00Z",
    updated_at: "2024-02-25T09:50:00Z",
    employee_id: 11,
    type: "behavioural",
    description: "Mindfulness app daily reminders",
    status: "completed",
    completed_at: null,
    completed_at: "2024-02-25T09:50:00Z",
    priority: "medium",
    source: "admin",
    notes: "Employee reported better focus",
    creator_admin_id: 1,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-02-20T09:00:00Z",
    updated_at: "2024-02-27T08:30:00Z",
    employee_id: 12,
    type: "exercise",
    description: "Back-strengthening exercise videos",
    status: "pending",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "Employee received instructions",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-02-21T14:30:00Z",
    updated_at: "2024-02-28T13:40:00Z",
    employee_id: 13,
    type: "equipment",
    description: "Noise-cancelling headphones",
    status: "in_progress",
    completed_at: null,
    priority: "high",
    source: "admin",
    notes: "Order placed",
    creator_admin_id: 1,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-02-23T15:00:00Z",
    updated_at: "2024-03-01T16:20:00Z",
    employee_id: 14,
    type: "behavioural",
    description: "Encourage cycling to work",
    status: "completed",
    completed_at: null,
    completed_at: "2024-03-01T16:20:00Z",
    priority: "medium",
    source: "vida",
    notes: "Employee joined bike-to-work scheme",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-02-25T08:45:00Z",
    updated_at: "2024-03-03T10:30:00Z",
    employee_id: 15,
    type: "exercise",
    description: "Stretch break reminders",
    status: "overdue",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "App not installed yet",
    creator_admin_id: null,
    last_updater_admin_id: 1,
  },
  {
    created_at: "2024-02-26T11:20:00Z",
    updated_at: "2024-03-05T14:15:00Z",
    employee_id: 16,
    type: "equipment",
    description: "Second monitor setup",
    status: "completed",
    completed_at: null,
    completed_at: "2024-03-05T14:15:00Z",
    priority: "high",
    source: "admin",
    notes: "Delivered",
    creator_admin_id: 1,
    last_updater_admin_id: 1,
  },
  {
    created_at: "2024-02-28T09:30:00Z",
    updated_at: "2024-03-07T11:00:00Z",
    employee_id: 17,
    type: "behavioural",
    description: "Encourage using stairs instead of lifts",
    status: "pending",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "Employee has started gradually",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-08T12:20:00Z",
    employee_id: 18,
    type: "exercise",
    description: "Weekly swimming sessions",
    status: "in_progress",
    completed_at: null,
    priority: "medium",
    source: "admin",
    notes: "Employee registered with pool membership",
    creator_admin_id: 1,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-03-02T13:00:00Z",
    updated_at: "2024-03-09T14:45:00Z",
    employee_id: 19,
    type: "equipment",
    description: "Anti-glare screen filter",
    status: "pending",
    completed_at: null,
    priority: "low",
    source: "vida",
    notes: "Procurement pending",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-03-03T15:30:00Z",
    updated_at: "2024-03-10T16:00:00Z",
    employee_id: 20,
    type: "behavioural",
    description: "Encourage standing phone calls",
    status: "completed",
    completed_at: null,
    completed_at: "2024-03-10T16:00:00Z",
    priority: "medium",
    source: "admin",
    notes: "Employee following regularly",
    creator_admin_id: 2,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-03-04T12:00:00Z",
    updated_at: "2024-03-12T10:45:00Z",
    employee_id: 21,
    type: "exercise",
    description: "Balance board sessions twice weekly",
    status: "pending",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "Scheduled",
    creator_admin_id: null,
    last_updater_admin_id: 1,
  },
  {
    created_at: "2024-03-06T09:00:00Z",
    updated_at: "2024-03-14T13:00:00Z",
    employee_id: 22,
    type: "equipment",
    description: "Footrest for desk comfort",
    status: "in_progress",
    completed_at: null,
    priority: "low",
    source: "admin",
    notes: "Waiting for delivery",
    creator_admin_id: 2,
    last_updater_admin_id: 1,
  },
  {
    created_at: "2024-03-07T14:15:00Z",
    updated_at: "2024-03-15T12:20:00Z",
    employee_id: 23,
    type: "behavioural",
    description: "Encourage hydration breaks",
    status: "pending",
    completed_at: null,
    priority: "medium",
    source: "vida",
    notes: "App reminder enabled",
    creator_admin_id: null,
    last_updater_admin_id: null,
  },
  {
    created_at: "2024-03-09T11:30:00Z",
    updated_at: "2024-03-17T09:30:00Z",
    employee_id: 24,
    type: "exercise",
    description: "Pilates class weekly",
    status: "in_progress",
    completed_at: null,
    priority: "high",
    source: "admin",
    notes: "Employee registered at studio",
    creator_admin_id: 1,
    last_updater_admin_id: 2,
  },
  {
    created_at: "2024-03-10T13:45:00Z",
    updated_at: "2024-03-18T11:15:00Z",
    employee_id: 25,
    type: "equipment",
    description: "Laptop stand for ergonomic posture",
    status: "completed",
    completed_at: null,
    completed_at: "2024-03-18T11:15:00Z",
    priority: "high",
    source: "vida",
    notes: "Employee confirmed improvement",
    creator_admin_id: null,
    last_updater_admin_id: 2,
  },
];

db.prepare(`DELETE FROM suggestions`).run();

const insertSuggestion = db.prepare(`
    INSERT INTO suggestions (created_at, updated_at, employee_id, type, description, status, completed_at, priority, source, notes, creator_admin_id, last_updater_admin_id)
    VALUES (@created_at, @updated_at, @employee_id, @type, @description, @status, @completed_at, @priority, @source, @notes, @creator_admin_id, @last_updater_admin_id)
`);

const insertManySuggestions = db.transaction((rows) => {
  for (const row of rows) insertSuggestion.run(row);
});

insertManySuggestions(suggestions);

console.log("✅ Database seeded with suggestions!");
